### ISSUE TITLE
[TextField] Should not allow new line

### ISSUE THREAD

**Issue by RUSshy** [rds1983/Myra#16]
Hello

TextField should be single line only, for quick inputs like login or password

For multi-line there should be a specific type: TextArea

Because right now, the text on TextField is never centered vertically

![bug](https://cloud.githubusercontent.com/assets/18348637/24772442/a392821e-1b11-11e7-9d4d-e4a9e5c817b9.png)

**Comment by rds1983** [comment]
Yeah, makes sense.

**Comment by rds1983** [comment]
I've added IsMultiline property for the TextField widget. Default value is false.
