### ISSUE TITLE
[Stylesheet] Make something like libGDX skin

### ISSUE THREAD

**Issue by RUSshy** [rds1983/Myra#17]
Hello,

If we take structure of Skin from libGDX it can looks like this:

```json
  "com.badlogic.gdx.scenes.scene2d.ui.TextButton$TextButtonStyle": {
    "default": {
      "down": "default-round-down",
      "up": "default-round",
      "font": "default-font",
      "fontColor": "white",
      "over": "default-over"
    },
    "toggle": {
      "down": "default-round-down",
      "up": "default-round",
      "checked": "default-round-down",
      "font": "default-font",
      "fontColor": "white",
      "downFontColor": "red"
    },
    "close": {
      "down": "btn-close-down",
      "up": "btn-close-up",
      "over": "btn-close-over",
      "font": "default-font",

      "fontColor": "white"
    }
  },
```

This allow us to access already 3 different styles, wich helps a lot when creating UI

i want close button ? new TextButton("X", "close") 
1st param is label of button, 2nd is the name of the style

Currently with Myra only one style is in the json:

```json
    "button": {
        "padding": {
            "left": 5.0,
            "right": 5.0
        },
        "background": "default-round",
        "pressedBackground": "default-round-down",
        "label": {
            "font": "default-font",
            "textColor": "white",
            "disabledTextColor": "grey"
        }
    },
```

This is very limiting, and i'm still not sure how i should do to handle multiple styles

Did i missed something?

Are you OK if we go with something like libGDX?

**Comment by rds1983** [comment]
yes, of course.
Though, I would want json to be look like following:
```json
"button": {
        ...
        "background": "default-round",
        "label": {
          ...
        },
       "styles": {
          "red": {
            "background": "default-red",
            "label": ...
          },
          "blue": {
            "background": "default-blue",
            "label": ...
          }        
        }
  }
```

**Comment by RUSshy** [comment]
I think it makes more sense to do like libGDX otherwise i'm not really sure how to correctly implement it, here is what i did so far:

https://gist.github.com/RUSshy/0882c042846412750b662b626d5e872f

I created a new loader and a new type SkinLoader & Skin

**Comment by rds1983** [comment]
Right now, in Myra you can do following:
```c#
DefaultAssets.UIStylesheet.HorizontalMenuStyle.MenuItemStyle.LabelStyle.TextColor = Color.Yellow;
```
I.e. easily change UI stylesheet in the code. We'll lose that ability if switch [Stylesheet](https://github.com/rds1983/Myra/blob/master/Source/Myra/Graphics2D/UI/Styles/Stylesheet.cs) to your Skin class.
Also Myra had been out for a while. And I think some people might already get used to the existing JSON format.

However as I said earlier I am totally supporting idea of adding custom styles to the stylesheet. But it must preserve as much as possible current Stylesheet class as well as its JSON representation.

**Comment by RUSshy** [comment]
I think most of the Styles will need to be re-written, because some of them store directly a reference of a Style :/

Myra WindowStyle:
```csharp
	public class WindowStyle: WidgetStyle
	{
		public TextBlockStyle TitleStyle { get; set; }
		public ImageButtonStyle CloseButtonStyle { get; set; }

		public WindowStyle()
		{
			TitleStyle = new TextBlockStyle();
			CloseButtonStyle = new ImageButtonStyle();
		}
	}
```

libGDX WindowStyle:

```java
	static public class WindowStyle {
		/** Optional. */
		public Drawable background;
		public BitmapFont titleFont;
		/** Optional. */
		public Color titleFontColor = new Color(1, 1, 1, 1);
		/** Optional. */
		public Drawable stageBackground;

		public WindowStyle () {
		}

		public WindowStyle (BitmapFont titleFont, Color titleFontColor, Drawable background) {
			this.background = background;
			this.titleFont = titleFont;
			this.titleFontColor.set(titleFontColor);
		}

		public WindowStyle (WindowStyle style) {
			this.background = style.background;
			this.titleFont = style.titleFont;
			this.titleFontColor = new Color(style.titleFontColor);
		}
	}
```

This will make it hard to specify custom styles, not sure how i could do :/

**Comment by RUSshy** [comment]
Breaking compatibility is i think needed in order to make the Stylesheet system more modular and data driven

**Comment by rds1983** [comment]
What's wrong with internally storing reference to the style?

Btw, probably you could add following properties to your Skin class:
```c#
private const string DefaultStyleName = "default";

public TextBlockStyle TextBlockStyle
{
  get {
    return (TextBlockStyle)Resources[typeof(TextBlockStyle)][DefaultStyleName];
  }
}
```

**Comment by rds1983** [comment]
And to resolve different JSON formats issue, how about we support both(existing Myra and one that you implement)?

**Comment by rds1983** [comment]
I realized what was problem with styles refering other styles. You want to load your JSON with JsonSerializer directly into Skin class. Yeah, it may be problematic with current styles architecture. 
Well, rewrite styles as much as you need to. Though [StylesheetLoader](https://github.com/rds1983/Myra/blob/master/Source/Myra/Graphics2D/UI/Styles/StylesheetLoader.cs) would need to be updated too. Otherwise code wouldn't compile.

**Comment by rds1983** [comment]
Multiple variants of style can be declared for every widget in the new version 0.5.6. I.e.:
```json
"textButton": {
        "background": "button",
        "pressedBackground": "button-down",
        "overBackground": "button-over",
        "label": {
            "font": "default-font",
            "textColor": "white",
            "disabledTextColor": "grey"
        },
        "variants": {
            "blue": { 
                "background": "button-blue",
                "pressedBackground": "button-blue-down",
                "overBackground": "button-blue-down"
            }
        }
    }
```
'blue' is style variant for TextButton widget. The corresponding TextButton could be created with following code:
```c#
var textButton = new TextButton("blue");
```
New feature is supported in the UI Editor:
![style variants](https://user-images.githubusercontent.com/1057289/34586126-4e69e55c-f1d5-11e7-88f2-c488204eb006.gif)
