### ISSUE TITLE
Submenu Items not opening is same position as the parent menu

### ISSUE THREAD

**Issue by prosthetichead** [rds1983/Myra#355]
I have noticed in 1.4 the submenu items do not open with the parent menu and seem to always open at the very top of the screen.

![unknown](https://user-images.githubusercontent.com/1934681/168776031-36e9d88c-3008-42ed-937c-c5ae8598fac3.png)
This sub menus parent is the horizontal menu at the bottom of the screen but it is opening attached  to Myra Pad's menu, this also happens to menu items opened from the top file menu.
![unknown](https://user-images.githubusercontent.com/1934681/168776411-510dfa6a-47cd-4b29-b6ae-c96731b41dc7.png)
![unknown](https://user-images.githubusercontent.com/1934681/168776714-6079fe55-4d43-48bc-9da6-36c26e6e5f0d.png)

**Comment by rds1983** [comment]
Should be fixed in 1.4.1
