### ISSUE TITLE
Tip: Set the <OutputType> in your csproj to WinExe to get rid of the debug console

### ISSUE THREAD

**Issue by Thraka** [rds1983/Myra#359]
When you start your examples, the annoying console pops up in the background. Set the project output to WinExe to avoid that. It works on all platforms even though it's "Win"Exe.

```xml
    <OutputType>WinExe</OutputType>
```

Just wanted to say cool project. I'm looking possibly using it as a debugger that can popup in the background of my game engine so that others can inspect game objects and the such. Possibly use it for more. My game engine has its own UI system, but it's not built to scale cleanly as my engine is a "text" engine.

I've been working with ImGui but it's just a huge pain to get working correctly.

https://github.com/Thraka/SadConsole/

**Comment by rds1983** [comment]
The console pop up has one single purpose - to report any startup failure(i.e. absence of any dependent library).
If I change the OutputType to "WinExe", then running of any startup-broken sample would result in it not reporting anything when run.

And, yeah, I saw the SadConsole. Great library too!
