### ISSUE TITLE
UI inside of TabItems doesn't change when clicking tabs in TabControl

### ISSUE THREAD

**Issue by Machaira** [rds1983/Myra#362]
I have the following MML:

<Project>
	<Panel Id="PowersPanel">
		<Label Text="Powerset Points:" Top="100" Left="25"/>
		<Label Id="PowersetPoints" Text="0" Top="100" Left="200"/>
		<TabControl Top="125" Left="25">
			<TabItem Text="Powersets">
				<Grid Id="PowersetsGrid">
					<Grid.ColumnsProportions>
						<Proportion Type="Auto"/>
						<Proportion Type="Pixels" Value="100"/>
						<Proportion Type="Pixels" Value="200"/>
					</Grid.ColumnsProportions>
					<Grid.DefaultRowProportion Type="Auto" />

					<Label Text="Powerset:" GridColumn="0" GridRow="1" />
					<ComboBox Id="PowersetsComboBox" Width="200" GridRow="1" GridColumn="1" />
					<Button Id="SelectPowersetButton" Text ="Select" GridRow="1" GridColumn="2"/>
					<Label Text="Selected Powersets:" GridRow ="1" GridColumn="3" />
					<ComboBox Id="PowersetsComboBox" Width="200" GridRow="1" GridColumn="4" />
					<Button Id="DeselectPowersetButton" Text ="De-Select" GridRow="1" GridColumn="5"/>

					<Label Text="Description:" GridRow="2" GridColumn ="0" />
					<Label Text="" GridRow="2" GridColumn ="1" GridColumnSpan="2"  />
					<Label Text="Suggested Origins:" GridRow="2" GridColumn="3" />
					<Label Text="" GridRow="2" GridColumn ="1" GridColumnSpan="2" />
				</Grid>
			</TabItem>
			<TabItem Text="Powers">
				<Grid Id="PowersGrid">
					<Grid.ColumnsProportions>
						<Proportion Type="Auto"/>
						<Proportion Type="Pixels" Value="100"/>
						<Proportion Type="Pixels" Value="200"/>
					</Grid.ColumnsProportions>
					<Grid.DefaultRowProportion Type="Auto" />

					<Label Text="Powerset:" GridColumn="0" GridRow="1" />
					<ComboBox Id="PowersetsComboBox" Width="200" GridRow="1" GridColumn="1" />
					<Button Id="SelectPowersetButton" Text ="Select" GridRow="1" GridColumn="2"/>
					<Label Text="Selected Powersets:" GridRow ="1" GridColumn="3" />
					<ComboBox Id="PowersetsComboBox" Width="200" GridRow="1" GridColumn="4" />
					<Button Id="DeselectPowersetButton" Text ="De-Select" GridRow="1" GridColumn="5"/>

					<Label Text="Description:" GridRow="2" GridColumn ="0" />
					<Label Text="" GridRow="2" GridColumn ="1" GridColumnSpan="2"  />
					<Label Text="Suggested Origins:" GridRow="2" GridColumn="3" />
					<Label Text="" GridRow="2" GridColumn ="1" GridColumnSpan="2" />
				</Grid>
			</TabItem>
		</TabControl>
	</Panel>
</Project>

The rendering is done by a base class:

`
        public override void Draw(GameTime gameTime)
        {
            ScreenManager.GraphicsDevice.Clear(ClearOptions.Target, Color.Black, 0, 0);

            var spriteBatch = ScreenManager.SpriteBatch;

            spriteBatch.Begin();

            if(activated)
            {
                tabs[curTab].Draw(gameTime);
                desktop.Render();
            }

            spriteBatch.End();
        }`

Which shows as

![image](https://user-images.githubusercontent.com/1019165/179547475-eb9973fc-3772-4179-96d5-818109afe32b.png)

Clicking the 2nd tab does not change what's rendered inside the TabControl. Is this normal? Is there something I should be doing to change what's rendered inside the TabControl?

**Comment by rds1983** [comment]
Hi,
The MML you've provided is incomplete. Though it looks fine.
There's stock tab sample MML: https://github.com/rds1983/Myra/blob/master/samples/UI/tabs.xmmp
I've pasted it into MyraPad and the TabControl worked as expected(you could switch tabs through clicking).

btw, I recommend moving call of desktop.Render() beyond spriteBatch.Begin()/spriteBatch.End().

**Comment by Machaira** [comment]
Can you let me know what's incomplete about it? I must be missing something. :(

**Comment by rds1983** [comment]
Oh, it was complete actually. Though for some reason, the browser showed me only part of it.
Anyway, both tabs of your TabControl have same content. Hence there's no change when switching between tabs.

**Comment by Machaira** [comment]
You are correct. My error. :( TabControl works correctly.
