### ISSUE TITLE
Feature Request: Create a UWP package

### ISSUE THREAD

**Issue by yesseruser** [rds1983/Myra#429]
Create/Port the Myra NuGet package to download in UWP applications.
Here's an article describing how to create a NuGet package for UWP: https://learn.microsoft.com/en-us/nuget/guides/create-uwp-packages-cs

When trying to install Myra (with MonoGame) in a UWP project, the installation stops and says the package is incompatible with the project.
This issue only occurs when trying to install Mira 1.5.0+, 1.4.5 works fine.
Here is a translated output when trying to install the package with the VS2022 Nuget package manager:
```
Package Myra 1.5.1 not compatible with uap10.0.16299 (UAP,Version=v10.0.16299) / <arch>. Package Myra 1.5.1 supports: net6.0 (.NETCoreAPP,Version=v6.0)
```
This message shows 9 times with `<arch>` being changed to:
1. nothing (the `/` isn't shown there)
2. `win10-arm`
3. `win10-arm-aot`
4. `win10-arm64`
5. `win10-arm64-aot`
6. `win10-x64`
7. `win10-x64-aot`
8. `win10-x86`
9. `win10-x86-aot`
Here's a link to a GitHub repository that uses UWP and Mira: https://github.com/Yesser-Studios/Pong-CSharp

**Comment by rds1983** [comment]
Should be fixed in Myra 1.5.2, where target framework had been downgraded to .net standard 2.0
