### ISSUE TITLE
Increasing FontResolutionFactor in FontSystemDefaults gives unwanted caret separation in Textbox component

### ISSUE THREAD

**Issue by GlitchyPSIX** [rds1983/Myra#461]
![image](https://github.com/rds1983/Myra/assets/11571952/69da13e7-566e-457f-82e3-5e75187913c4)
Here the Resolution Factor was set and remained at 4. The caret in the input is very far away from where it is (there are no spaces after "4".)

This is only visible in the last character.

**Comment by rds1983** [comment]
Should be fixed after moving unto FontStashSharp 1.3.9
