### ISSUE TITLE
CheckBox - onCheck event?

### ISSUE THREAD

**Issue by Kubrix** [rds1983/Myra#468]
Could not find the onCheck event for CheckBox.

**Comment by rds1983** [comment]
IsCheckedChanged

**Comment by Kubrix** [comment]
No?
![image](https://github.com/user-attachments/assets/dbc5183c-3839-4ed1-8cca-5377e3ea5e87)

**Comment by rds1983** [comment]
oh, mixed it with CheckButton. CheckBox has PressedChanged.
Anyway, it's recommended to use CheckButton, since CheckBox is deprecated.

**Comment by Kubrix** [comment]
I think you meant **PressedChanged**

**Comment by Kubrix** [comment]
Thanks
